### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by MatteoAndriolo** [MatteoAndriolo/Neural_Dependency_Parsing#3]
### arceagerparser
- [ ] movements {parser}
- [ ] movements selections {oracle}

### utils.py
- [ ]  is_projective
- [ ] generate_gold_path_moves
- [ ] parse_step {correctness of moves and conditions}
- [ ] 

### general
- [ ] training
- [ ] test
- [ ] evaluate

### BiLSTM
prepare_batch
- [ ] encoding sentence
- [ ] create_dictionary
- [ ] generate_gold_path_moves

NN
- [ ] forward logic
- [ ] inference logic 

### BERT
Management of word tokenization
- [ ]  match_subtokens
- [ ] merge_splitted_tokens
- [ ] tokens_tokenizer_correspondence

prepare batch
- [ ] tokenizer
- [ ] get_configurations {configuration, moves, head }
- [ ]  tokens_tokenizer_correspondence {correspondences}

NN
- [ ] forward logic
- [ ] inference logic

**Comment by MatteoAndriolo** [comment]
Try using small mlp, 0.10*|h|
